"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var File_1 = require("./File");
var Directory_1 = require("./Directory");
var rootDirectory = new Directory_1.Directory("root");
var notAVirus = new File_1.File("NotAVirus.exe");
rootDirectory.addFile(notAVirus);
var usersDirectory = new Directory_1.Directory("users");
rootDirectory.addFile(usersDirectory);
var userOneDirectory = new Directory_1.Directory("User-One");
usersDirectory.addFile(userOneDirectory);
rootDirectory.inspect();
var userOneImagesDirectory = new Directory_1.Directory("Images");
userOneDirectory.addFile(userOneImagesDirectory);
var catImages = new Directory_1.Directory("Cat Images");
userOneImagesDirectory.addFile(catImages);
var catImageOne = new File_1.File("Cat Image One");
var catImageTwo = new File_1.File("Cat Image Two");
catImages.addFile(catImageOne);
catImages.addFile(catImageTwo);
catImages.inspect();
var imageOne = new File_1.File("Image One");
userOneImagesDirectory.addFile(imageOne);
var imageTwo = new File_1.File("Image Two");
userOneImagesDirectory.addFile(imageTwo);
var imageThree = new File_1.File("Image Three");
userOneImagesDirectory.addFile(imageThree);
userOneImagesDirectory.inspect();
var superSecretTextFile = new File_1.File("Super Secret Text File");
userOneDirectory.addFile(superSecretTextFile);
userOneDirectory.inspect();
var userTwoDirectory = new Directory_1.Directory("User-Two");
usersDirectory.addFile(userTwoDirectory);
var taxesFile = new File_1.File("Taxes File");
taxesFile.inspect();
userTwoDirectory.addFile(taxesFile);
userTwoDirectory.inspect();
var userThreeDirectory = new Directory_1.Directory("User-Three");
usersDirectory.addFile(userThreeDirectory);
var userThreeImagesDirectory = new Directory_1.Directory("Images");
userThreeDirectory.addFile(userThreeImagesDirectory);
var dogOne = new File_1.File("Dog Image");
userThreeImagesDirectory.addFile(dogOne);
userThreeImagesDirectory.inspect();
userThreeDirectory.inspect();
